name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - mlflow
  - numpy
  - pip:
    - azureml-defaults
    - joblib
    - sklearn
    - inference-schema
    - inference-schema[numpy-support]
